export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';

export const TODO_TEXT_CHANGED = 'TODO_TEXT_CHANGED';
export const TOGGLE_SHOW_COMPLETED = 'TOGGLE_SHOW_COMPLETED';
