export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';

export const TODO_SCREEN_TOGGLE_COMPLETED = 'TODO_SCREEN_TOGGLE_VISIBLE';
export const TODO_SCREEN_TODO_TEXT_CHANGED = 'TODO_SCREEN_TODO_TEXT_CHANGED';
